version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invec_app
    ports:
      - "8000:80"
      - "5173:5173"   # <--- Este es Vite
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: invec_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: invec
      MYSQL_USER: invec
      MYSQL_PASSWORD: invec123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
